"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# env settings
env = environ.Env()
environ.Env.read_env(BASE_DIR.parent.joinpath('.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # My
    'accounts.apps.AccountsConfig',
    'classroom.apps.ClassroomConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': env.db(),
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# Media

MEDIA_ROOT = BASE_DIR / 'media/'
MEDIA_URL = 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom Auth
AUTH_USER_MODEL = 'accounts.CustomUser'

# My settings

NAME_DB_ADMIN_GROUP = 'admin'
NAME_ADMIN_GROUP = 'Администратор'
NAME_DB_PARTNER_GROUP = 'partner'
NAME_PARTNER_GROUP = 'Партнер'
NAME_DB_TEACHER_GROUP = 'teacher'
NAME_TEACHER_GROUP = 'Учитель'
NAME_DB_STUDENT_GROUP = 'student'
NAME_STUDENT_GROUP = 'Студент'

NAME_DB_NOT_VERIFIED_PARTNER_GROUP = 'not_verified_partner'
NAME_NOT_VERIFIED_PARTNER_GROUP = 'Не подтвержденный партнер'
NAME_DB_NOT_VERIFIED_TEACHER_GROUP = 'not_verified_teacher'
NAME_NOT_VERIFIED_TEACHER_GROUP = 'Не подтвержденный учитель'

ALL_GROUPS = {
    # Name_DB: Name
    NAME_DB_ADMIN_GROUP: NAME_ADMIN_GROUP,
    NAME_DB_PARTNER_GROUP: NAME_PARTNER_GROUP,
    NAME_DB_TEACHER_GROUP: NAME_TEACHER_GROUP,
    NAME_DB_STUDENT_GROUP: NAME_STUDENT_GROUP,
    NAME_DB_NOT_VERIFIED_PARTNER_GROUP: NAME_NOT_VERIFIED_PARTNER_GROUP,
    NAME_DB_NOT_VERIFIED_TEACHER_GROUP: NAME_NOT_VERIFIED_TEACHER_GROUP,
}

TEXT_ADRESS_ABOUT_CITY = 'Улица 123, Красноярск, РФ'
TEXT_ABOUT_EMAIL = 'zalmon74@yandex.ru'
TEXT_ABOUT_NUMBER_PHONE = '+7(123) 456-78-90'
