# Generated by Django 4.1.7 on 2023-05-08 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(help_text='Может имееть значение от 1 до 10', verbose_name='Оценка')),
                ('grade_comment', models.TextField(blank=True, help_text='Может быть пустым', verbose_name='Комментарий')),
                ('f_deleted', models.BooleanField(default=False, help_text='Устанавливается, когда комментарий удаляется администратором', verbose_name='Флаг удаленного комментарий')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания отзыва')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата последнего редактирования')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
                ('course', models.ForeignKey(help_text='Курс, к которому пишется отзыв', on_delete=django.db.models.deletion.PROTECT, to='training_course.trainingcoursemodel', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Отзыв к курсу',
                'verbose_name_plural': 'Отзывы к курсам',
            },
        ),
        migrations.CreateModel(
            name='MoreInformationAboutCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('course_program', models.TextField(help_text='План, по которому будут заниматься ученики (студенты)', verbose_name='Программа курса')),
                ('course', models.OneToOneField(help_text='Курс, к которому относится дополнительная информация', on_delete=django.db.models.deletion.PROTECT, to='training_course.trainingcoursemodel', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Дополнительна информация о курсе',
                'verbose_name_plural': 'Дополнительна информация о курсах',
            },
        ),
        migrations.AddConstraint(
            model_name='reviewcourse',
            constraint=models.CheckConstraint(check=models.Q(('grade__gt', 0), ('grade__lt', 11)), name='check_grade__gt_0_and__lt_11', violation_error_message='Оценка может иметь диапозон значений от 1 до 10'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewcourse',
            unique_together={('course', 'author')},
        ),
    ]
