# Generated by Django 4.1.7 on 2023-05-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_course', '0003_moreinformationaboutteachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='categories',
            field=models.ManyToManyField(help_text='К какой категории относится тег', to='training_course.category', verbose_name='Категория'),
        ),
    ]
