# Generated by Django 4.1.7 on 2023-04-15 08:34

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='url_email',
            field=models.URLField(blank=True, null=True, validators=[accounts.validators.validation_url_mail], verbose_name='Ссылка на профиль в почтовом сервисе'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='url_github',
            field=models.URLField(blank=True, null=True, validators=[accounts.validators.validation_url_github], verbose_name='Ссылка на профиль на github'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='url_vk',
            field=models.URLField(blank=True, null=True, validators=[accounts.validators.validation_url_vk], verbose_name='Ссылка на профиль в VK'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(help_text='Фамилия пользователя может иметь максимум 50 символов и содержать только русские и латинские буквы', max_length=50, validators=[accounts.validators.validation_first_second_sur_name], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default='', help_text='Отчество пользователя может иметь максимум 50 символов и содержать только русские и латинские буквы', max_length=50, validators=[accounts.validators.validation_first_second_sur_name], verbose_name='Отчество'),
        ),
    ]
