# Generated by Django 4.1.7 on 2023-04-15 14:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('subject', models.CharField(max_length=70, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('sent_date', models.DateField(auto_now_add=True, verbose_name='Дата отправления')),
            ],
            options={
                'verbose_name': 'Сообщение со страницы "Связаться с нами"',
                'verbose_name_plural': 'Сообщения со страницы "Связаться с нами"',
            },
        ),
    ]
